CREATE SCHEMA "app_private";
--> statement-breakpoint
CREATE TYPE "app_private"."activity_events_outcome" AS ENUM('success', 'failure');--> statement-breakpoint
CREATE TYPE "app_private"."brand_assets_status" AS ENUM('pending', 'approved', 'rejected');--> statement-breakpoint
CREATE TYPE "app_private"."brand_assets_type" AS ENUM('logo', 'font', 'product', 'reference', 'other');--> statement-breakpoint
CREATE TYPE "app_private"."brand_kits_status" AS ENUM('draft', 'active');--> statement-breakpoint
CREATE TYPE "app_private"."campaign_briefs_channel" AS ENUM('meta', 'google_display', 'microsoft', 'multi_channel');--> statement-breakpoint
CREATE TYPE "app_private"."campaign_briefs_status" AS ENUM('draft', 'in_review', 'approved', 'rejected');--> statement-breakpoint
CREATE TYPE "app_private"."creative_jobs_status" AS ENUM('queued', 'running', 'completed', 'failed');--> statement-breakpoint
CREATE TYPE "app_private"."creative_variants_channel" AS ENUM('meta', 'google_display', 'microsoft');--> statement-breakpoint
CREATE TYPE "app_private"."creative_variants_status" AS ENUM('pending', 'approved', 'rejected');--> statement-breakpoint
CREATE TYPE "app_private"."meta_connections_status" AS ENUM('disconnected', 'connected', 'error');--> statement-breakpoint
CREATE TYPE "app_private"."organization_invites_role" AS ENUM('admin', 'creator', 'reviewer', 'publisher');--> statement-breakpoint
CREATE TYPE "app_private"."organization_invites_status" AS ENUM('pending', 'accepted', 'revoked');--> statement-breakpoint
CREATE TYPE "app_private"."organization_memberships_role" AS ENUM('owner', 'admin', 'creator', 'reviewer', 'publisher');--> statement-breakpoint
CREATE TYPE "app_private"."organization_memberships_status" AS ENUM('invited', 'active', 'suspended');--> statement-breakpoint
CREATE TYPE "app_private"."products_recordType" AS ENUM('family', 'standalone', 'accessory', 'material', 'software', 'service', 'bundle');--> statement-breakpoint
CREATE TYPE "app_private"."products_status" AS ENUM('pending', 'approved', 'rejected');--> statement-breakpoint
CREATE TYPE "app_private"."publish_requests_action" AS ENUM('create', 'update');--> statement-breakpoint
CREATE TYPE "app_private"."publish_requests_status" AS ENUM('draft', 'awaiting_approval', 'approved', 'publishing', 'published', 'failed', 'cancelled');--> statement-breakpoint
CREATE TYPE "app_private"."review_comments_status" AS ENUM('open', 'resolved');--> statement-breakpoint
CREATE TYPE "app_private"."users_role" AS ENUM('user', 'admin');--> statement-breakpoint
CREATE TYPE "app_private"."website_crawl_jobs_scanMode" AS ENUM('brand_and_products', 'products_only');--> statement-breakpoint
CREATE TYPE "app_private"."website_crawl_jobs_status" AS ENUM('queued', 'discovering', 'crawling', 'analyzing', 'review_ready', 'completed', 'failed', 'cancelled');--> statement-breakpoint
CREATE TYPE "app_private"."website_crawl_pages_pageType" AS ENUM('home', 'product', 'collection', 'about', 'contact', 'other');--> statement-breakpoint
CREATE TYPE "app_private"."website_crawl_pages_status" AS ENUM('fetched', 'analyzed', 'failed');--> statement-breakpoint
CREATE TABLE "app_private"."activity_events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_private"."activity_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organizationId" integer NOT NULL,
	"actorUserId" integer NOT NULL,
	"action" varchar(120) NOT NULL,
	"entityType" varchar(80) NOT NULL,
	"entityId" varchar(120) NOT NULL,
	"outcome" "app_private"."activity_events_outcome" DEFAULT 'success' NOT NULL,
	"payload" json,
	"correlationId" varchar(96) NOT NULL,
	"previousHash" varchar(64),
	"eventHash" varchar(64) NOT NULL,
	"createdAtMs" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_private"."brand_assets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_private"."brand_assets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organizationId" integer NOT NULL,
	"brandKitId" integer NOT NULL,
	"name" varchar(180) NOT NULL,
	"type" "app_private"."brand_assets_type" NOT NULL,
	"storageKey" varchar(500) NOT NULL,
	"url" text NOT NULL,
	"mimeType" varchar(100) NOT NULL,
	"status" "app_private"."brand_assets_status" DEFAULT 'pending' NOT NULL,
	"metadata" json,
	"uploadedByUserId" integer NOT NULL,
	"reviewedByUserId" integer,
	"reviewedAtMs" bigint,
	"createdAtMs" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_private"."brand_kits" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_private"."brand_kits_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organizationId" integer NOT NULL,
	"name" varchar(160) NOT NULL,
	"voice" text,
	"colors" json NOT NULL,
	"fonts" json NOT NULL,
	"requiredClaims" text,
	"prohibitedContent" text,
	"status" "app_private"."brand_kits_status" DEFAULT 'draft' NOT NULL,
	"updatedByUserId" integer NOT NULL,
	"updatedAtMs" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_private"."campaign_briefs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_private"."campaign_briefs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organizationId" integer NOT NULL,
	"name" varchar(200) NOT NULL,
	"audience" text NOT NULL,
	"offer" text NOT NULL,
	"channel" "app_private"."campaign_briefs_channel" DEFAULT 'meta' NOT NULL,
	"creativeSetup" json,
	"placements" json NOT NULL,
	"formats" json NOT NULL,
	"creativeDirection" text NOT NULL,
	"destinationUrl" text,
	"requiredClaims" text,
	"assetIds" json NOT NULL,
	"productIds" json,
	"status" "app_private"."campaign_briefs_status" DEFAULT 'draft' NOT NULL,
	"createdByUserId" integer NOT NULL,
	"approvedByUserId" integer,
	"approvedAtMs" bigint,
	"createdAtMs" bigint NOT NULL,
	"updatedAtMs" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_private"."creative_jobs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_private"."creative_jobs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organizationId" integer NOT NULL,
	"briefId" integer NOT NULL,
	"status" "app_private"."creative_jobs_status" DEFAULT 'queued' NOT NULL,
	"inputHash" varchar(64) NOT NULL,
	"briefSnapshot" json NOT NULL,
	"assetSnapshot" json NOT NULL,
	"requestedByUserId" integer NOT NULL,
	"errorMessage" text,
	"leaseExpiresAtMs" bigint,
	"createdAtMs" bigint NOT NULL,
	"completedAtMs" bigint
);
--> statement-breakpoint
CREATE TABLE "app_private"."creative_variants" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_private"."creative_variants_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organizationId" integer NOT NULL,
	"jobId" integer NOT NULL,
	"briefId" integer NOT NULL,
	"name" varchar(180) NOT NULL,
	"concept" text NOT NULL,
	"primaryText" text NOT NULL,
	"headline" varchar(255) NOT NULL,
	"description" text,
	"callToAction" varchar(64) NOT NULL,
	"format" varchar(64) NOT NULL,
	"channel" "app_private"."creative_variants_channel" DEFAULT 'meta' NOT NULL,
	"imageUrl" text NOT NULL,
	"imageStorageKey" varchar(500),
	"renderMetadata" json,
	"status" "app_private"."creative_variants_status" DEFAULT 'pending' NOT NULL,
	"reviewedByUserId" integer,
	"reviewedAtMs" bigint,
	"createdAtMs" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_private"."meta_connections" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_private"."meta_connections_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organizationId" integer NOT NULL,
	"adAccountId" varchar(100) NOT NULL,
	"pageId" varchar(100),
	"instagramActorId" varchar(100),
	"accessTokenCiphertext" text,
	"tokenIv" varchar(64),
	"tokenTag" varchar(64),
	"status" "app_private"."meta_connections_status" DEFAULT 'disconnected' NOT NULL,
	"connectedByUserId" integer NOT NULL,
	"connectedAtMs" bigint,
	"updatedAtMs" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_private"."organization_invites" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_private"."organization_invites_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organizationId" integer NOT NULL,
	"email" varchar(320) NOT NULL,
	"role" "app_private"."organization_invites_role" NOT NULL,
	"token" varchar(96) NOT NULL,
	"status" "app_private"."organization_invites_status" DEFAULT 'pending' NOT NULL,
	"invitedByUserId" integer NOT NULL,
	"expiresAtMs" bigint NOT NULL,
	"createdAtMs" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_private"."organization_memberships" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_private"."organization_memberships_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organizationId" integer NOT NULL,
	"userId" integer NOT NULL,
	"role" "app_private"."organization_memberships_role" NOT NULL,
	"status" "app_private"."organization_memberships_status" DEFAULT 'active' NOT NULL,
	"createdAtMs" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_private"."organizations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_private"."organizations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(160) NOT NULL,
	"slug" varchar(180) NOT NULL,
	"createdByUserId" integer NOT NULL,
	"createdAtMs" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_private"."product_images" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_private"."product_images_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organizationId" integer NOT NULL,
	"productId" integer NOT NULL,
	"sourceUrl" text NOT NULL,
	"storageKey" varchar(500) NOT NULL,
	"url" text NOT NULL,
	"altText" varchar(500),
	"isPrimary" integer DEFAULT 0 NOT NULL,
	"createdAtMs" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_private"."product_variants" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_private"."product_variants_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organizationId" integer NOT NULL,
	"productId" integer NOT NULL,
	"sourceKey" varchar(64) NOT NULL,
	"name" varchar(500) NOT NULL,
	"sku" varchar(180),
	"price" varchar(80),
	"currency" varchar(16),
	"availability" varchar(120),
	"imageSourceUrl" text,
	"productUrl" text,
	"metadata" json,
	"createdAtMs" bigint NOT NULL,
	"updatedAtMs" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_private"."products" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_private"."products_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organizationId" integer NOT NULL,
	"crawlJobId" integer,
	"sourcePageId" integer,
	"name" varchar(300) NOT NULL,
	"dedupeKey" varchar(64) NOT NULL,
	"sku" varchar(180),
	"category" varchar(240),
	"recordType" "app_private"."products_recordType" DEFAULT 'standalone' NOT NULL,
	"variantCount" integer DEFAULT 0 NOT NULL,
	"description" text,
	"productUrl" text NOT NULL,
	"price" varchar(80),
	"currency" varchar(16),
	"specifications" json NOT NULL,
	"provenance" json NOT NULL,
	"status" "app_private"."products_status" DEFAULT 'pending' NOT NULL,
	"reviewedByUserId" integer,
	"reviewedAtMs" bigint,
	"createdAtMs" bigint NOT NULL,
	"updatedAtMs" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_private"."publish_requests" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_private"."publish_requests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organizationId" integer NOT NULL,
	"variantId" integer NOT NULL,
	"connectionId" integer NOT NULL,
	"action" "app_private"."publish_requests_action" NOT NULL,
	"payload" json NOT NULL,
	"payloadHash" varchar(64) NOT NULL,
	"approvedHash" varchar(64),
	"status" "app_private"."publish_requests_status" DEFAULT 'draft' NOT NULL,
	"createdByUserId" integer NOT NULL,
	"approvedByUserId" integer,
	"publishedByUserId" integer,
	"metaObjectId" varchar(150),
	"result" json,
	"approvedAtMs" bigint,
	"createdAtMs" bigint NOT NULL,
	"updatedAtMs" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_private"."review_comments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_private"."review_comments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organizationId" integer NOT NULL,
	"briefId" integer,
	"variantId" integer,
	"body" text NOT NULL,
	"status" "app_private"."review_comments_status" DEFAULT 'open' NOT NULL,
	"authorUserId" integer NOT NULL,
	"createdAtMs" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_private"."users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_private"."users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"authUserId" uuid,
	"openId" varchar(64) NOT NULL,
	"name" text,
	"email" varchar(320),
	"loginMethod" varchar(64),
	"role" "app_private"."users_role" DEFAULT 'user' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"lastSignedIn" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_authUserId_unique" UNIQUE("authUserId"),
	CONSTRAINT "users_openId_unique" UNIQUE("openId")
);
--> statement-breakpoint
CREATE TABLE "app_private"."website_crawl_jobs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_private"."website_crawl_jobs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organizationId" integer NOT NULL,
	"sourceUrl" text NOT NULL,
	"sourceOrigin" varchar(500) NOT NULL,
	"scanMode" "app_private"."website_crawl_jobs_scanMode" DEFAULT 'brand_and_products' NOT NULL,
	"status" "app_private"."website_crawl_jobs_status" DEFAULT 'queued' NOT NULL,
	"discoveredUrls" json NOT NULL,
	"cursor" integer DEFAULT 0 NOT NULL,
	"pagesDiscovered" integer DEFAULT 0 NOT NULL,
	"pagesProcessed" integer DEFAULT 0 NOT NULL,
	"maxPages" integer DEFAULT 100 NOT NULL,
	"brandDraft" json,
	"errorMessage" text,
	"createdByUserId" integer NOT NULL,
	"createdAtMs" bigint NOT NULL,
	"updatedAtMs" bigint NOT NULL,
	"completedAtMs" bigint
);
--> statement-breakpoint
CREATE TABLE "app_private"."website_crawl_pages" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_private"."website_crawl_pages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organizationId" integer NOT NULL,
	"jobId" integer NOT NULL,
	"url" text NOT NULL,
	"urlHash" varchar(64) NOT NULL,
	"canonicalUrl" text,
	"title" varchar(500),
	"pageType" "app_private"."website_crawl_pages_pageType" DEFAULT 'other' NOT NULL,
	"textContent" text,
	"metadata" json,
	"colors" json NOT NULL,
	"fonts" json NOT NULL,
	"imageUrls" json NOT NULL,
	"contentHash" varchar(64),
	"status" "app_private"."website_crawl_pages_status" DEFAULT 'fetched' NOT NULL,
	"errorMessage" text,
	"fetchedAtMs" bigint NOT NULL
);
--> statement-breakpoint
ALTER TABLE "app_private"."activity_events" ADD CONSTRAINT "activity_events_organizationId_organizations_id_fk" FOREIGN KEY ("organizationId") REFERENCES "app_private"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."activity_events" ADD CONSTRAINT "activity_events_actorUserId_users_id_fk" FOREIGN KEY ("actorUserId") REFERENCES "app_private"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."brand_assets" ADD CONSTRAINT "brand_assets_organizationId_organizations_id_fk" FOREIGN KEY ("organizationId") REFERENCES "app_private"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."brand_assets" ADD CONSTRAINT "brand_assets_brandKitId_brand_kits_id_fk" FOREIGN KEY ("brandKitId") REFERENCES "app_private"."brand_kits"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."brand_assets" ADD CONSTRAINT "brand_assets_uploadedByUserId_users_id_fk" FOREIGN KEY ("uploadedByUserId") REFERENCES "app_private"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."brand_assets" ADD CONSTRAINT "brand_assets_reviewedByUserId_users_id_fk" FOREIGN KEY ("reviewedByUserId") REFERENCES "app_private"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."brand_kits" ADD CONSTRAINT "brand_kits_organizationId_organizations_id_fk" FOREIGN KEY ("organizationId") REFERENCES "app_private"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."brand_kits" ADD CONSTRAINT "brand_kits_updatedByUserId_users_id_fk" FOREIGN KEY ("updatedByUserId") REFERENCES "app_private"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."campaign_briefs" ADD CONSTRAINT "campaign_briefs_organizationId_organizations_id_fk" FOREIGN KEY ("organizationId") REFERENCES "app_private"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."campaign_briefs" ADD CONSTRAINT "campaign_briefs_createdByUserId_users_id_fk" FOREIGN KEY ("createdByUserId") REFERENCES "app_private"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."campaign_briefs" ADD CONSTRAINT "campaign_briefs_approvedByUserId_users_id_fk" FOREIGN KEY ("approvedByUserId") REFERENCES "app_private"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."creative_jobs" ADD CONSTRAINT "creative_jobs_organizationId_organizations_id_fk" FOREIGN KEY ("organizationId") REFERENCES "app_private"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."creative_jobs" ADD CONSTRAINT "creative_jobs_briefId_campaign_briefs_id_fk" FOREIGN KEY ("briefId") REFERENCES "app_private"."campaign_briefs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."creative_jobs" ADD CONSTRAINT "creative_jobs_requestedByUserId_users_id_fk" FOREIGN KEY ("requestedByUserId") REFERENCES "app_private"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."creative_variants" ADD CONSTRAINT "creative_variants_organizationId_organizations_id_fk" FOREIGN KEY ("organizationId") REFERENCES "app_private"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."creative_variants" ADD CONSTRAINT "creative_variants_jobId_creative_jobs_id_fk" FOREIGN KEY ("jobId") REFERENCES "app_private"."creative_jobs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."creative_variants" ADD CONSTRAINT "creative_variants_briefId_campaign_briefs_id_fk" FOREIGN KEY ("briefId") REFERENCES "app_private"."campaign_briefs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."creative_variants" ADD CONSTRAINT "creative_variants_reviewedByUserId_users_id_fk" FOREIGN KEY ("reviewedByUserId") REFERENCES "app_private"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."meta_connections" ADD CONSTRAINT "meta_connections_organizationId_organizations_id_fk" FOREIGN KEY ("organizationId") REFERENCES "app_private"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."meta_connections" ADD CONSTRAINT "meta_connections_connectedByUserId_users_id_fk" FOREIGN KEY ("connectedByUserId") REFERENCES "app_private"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."organization_invites" ADD CONSTRAINT "organization_invites_organizationId_organizations_id_fk" FOREIGN KEY ("organizationId") REFERENCES "app_private"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."organization_invites" ADD CONSTRAINT "organization_invites_invitedByUserId_users_id_fk" FOREIGN KEY ("invitedByUserId") REFERENCES "app_private"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."organization_memberships" ADD CONSTRAINT "organization_memberships_organizationId_organizations_id_fk" FOREIGN KEY ("organizationId") REFERENCES "app_private"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."organization_memberships" ADD CONSTRAINT "organization_memberships_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "app_private"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."organizations" ADD CONSTRAINT "organizations_createdByUserId_users_id_fk" FOREIGN KEY ("createdByUserId") REFERENCES "app_private"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."product_images" ADD CONSTRAINT "product_images_organizationId_organizations_id_fk" FOREIGN KEY ("organizationId") REFERENCES "app_private"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."product_images" ADD CONSTRAINT "product_images_productId_products_id_fk" FOREIGN KEY ("productId") REFERENCES "app_private"."products"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."product_variants" ADD CONSTRAINT "product_variants_organizationId_organizations_id_fk" FOREIGN KEY ("organizationId") REFERENCES "app_private"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."product_variants" ADD CONSTRAINT "product_variants_productId_products_id_fk" FOREIGN KEY ("productId") REFERENCES "app_private"."products"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."products" ADD CONSTRAINT "products_organizationId_organizations_id_fk" FOREIGN KEY ("organizationId") REFERENCES "app_private"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."products" ADD CONSTRAINT "products_crawlJobId_website_crawl_jobs_id_fk" FOREIGN KEY ("crawlJobId") REFERENCES "app_private"."website_crawl_jobs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."products" ADD CONSTRAINT "products_sourcePageId_website_crawl_pages_id_fk" FOREIGN KEY ("sourcePageId") REFERENCES "app_private"."website_crawl_pages"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."products" ADD CONSTRAINT "products_reviewedByUserId_users_id_fk" FOREIGN KEY ("reviewedByUserId") REFERENCES "app_private"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."publish_requests" ADD CONSTRAINT "publish_requests_organizationId_organizations_id_fk" FOREIGN KEY ("organizationId") REFERENCES "app_private"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."publish_requests" ADD CONSTRAINT "publish_requests_variantId_creative_variants_id_fk" FOREIGN KEY ("variantId") REFERENCES "app_private"."creative_variants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."publish_requests" ADD CONSTRAINT "publish_requests_connectionId_meta_connections_id_fk" FOREIGN KEY ("connectionId") REFERENCES "app_private"."meta_connections"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."publish_requests" ADD CONSTRAINT "publish_requests_createdByUserId_users_id_fk" FOREIGN KEY ("createdByUserId") REFERENCES "app_private"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."publish_requests" ADD CONSTRAINT "publish_requests_approvedByUserId_users_id_fk" FOREIGN KEY ("approvedByUserId") REFERENCES "app_private"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."publish_requests" ADD CONSTRAINT "publish_requests_publishedByUserId_users_id_fk" FOREIGN KEY ("publishedByUserId") REFERENCES "app_private"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."review_comments" ADD CONSTRAINT "review_comments_organizationId_organizations_id_fk" FOREIGN KEY ("organizationId") REFERENCES "app_private"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."review_comments" ADD CONSTRAINT "review_comments_briefId_campaign_briefs_id_fk" FOREIGN KEY ("briefId") REFERENCES "app_private"."campaign_briefs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."review_comments" ADD CONSTRAINT "review_comments_variantId_creative_variants_id_fk" FOREIGN KEY ("variantId") REFERENCES "app_private"."creative_variants"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."review_comments" ADD CONSTRAINT "review_comments_authorUserId_users_id_fk" FOREIGN KEY ("authorUserId") REFERENCES "app_private"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."website_crawl_jobs" ADD CONSTRAINT "website_crawl_jobs_organizationId_organizations_id_fk" FOREIGN KEY ("organizationId") REFERENCES "app_private"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."website_crawl_jobs" ADD CONSTRAINT "website_crawl_jobs_createdByUserId_users_id_fk" FOREIGN KEY ("createdByUserId") REFERENCES "app_private"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."website_crawl_pages" ADD CONSTRAINT "website_crawl_pages_organizationId_organizations_id_fk" FOREIGN KEY ("organizationId") REFERENCES "app_private"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."website_crawl_pages" ADD CONSTRAINT "website_crawl_pages_jobId_website_crawl_jobs_id_fk" FOREIGN KEY ("jobId") REFERENCES "app_private"."website_crawl_jobs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "activity_event_hash_unique" ON "app_private"."activity_events" USING btree ("eventHash");--> statement-breakpoint
CREATE UNIQUE INDEX "brand_kit_organization_unique" ON "app_private"."brand_kits" USING btree ("organizationId");--> statement-breakpoint
CREATE UNIQUE INDEX "meta_connection_organization_unique" ON "app_private"."meta_connections" USING btree ("organizationId");--> statement-breakpoint
CREATE UNIQUE INDEX "organization_invite_token_unique" ON "app_private"."organization_invites" USING btree ("token");--> statement-breakpoint
CREATE UNIQUE INDEX "organization_member_unique" ON "app_private"."organization_memberships" USING btree ("organizationId","userId");--> statement-breakpoint
CREATE UNIQUE INDEX "organizations_slug_unique" ON "app_private"."organizations" USING btree ("slug");--> statement-breakpoint
CREATE UNIQUE INDEX "product_variant_source_unique" ON "app_private"."product_variants" USING btree ("organizationId","productId","sourceKey");--> statement-breakpoint
CREATE UNIQUE INDEX "product_organization_dedupe_unique" ON "app_private"."products" USING btree ("organizationId","dedupeKey");--> statement-breakpoint
CREATE UNIQUE INDEX "website_crawl_page_unique" ON "app_private"."website_crawl_pages" USING btree ("jobId","urlHash");