CREATE TABLE "app_private"."catalog_sources" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_private"."catalog_sources_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organizationId" integer NOT NULL,
	"provider" varchar(30) NOT NULL,
	"name" varchar(200) NOT NULL,
	"storeUrl" text NOT NULL,
	"credentials" json,
	"status" varchar(30) DEFAULT 'connected' NOT NULL,
	"cursor" text,
	"processed" integer DEFAULT 0 NOT NULL,
	"total" integer,
	"error" text,
	"leaseUntil" bigint,
	"autoSync" integer DEFAULT 1 NOT NULL,
	"lastSyncAt" bigint,
	"nextSyncAt" bigint,
	"createdByUserId" integer NOT NULL,
	"updatedAtMs" bigint NOT NULL
);
--> statement-breakpoint
ALTER TABLE "app_private"."products" ADD COLUMN "serviceDetails" json;--> statement-breakpoint
ALTER TABLE "app_private"."products" ADD COLUMN "sourceId" integer;--> statement-breakpoint
ALTER TABLE "app_private"."products" ADD COLUMN "externalId" varchar(300);--> statement-breakpoint
ALTER TABLE "app_private"."website_crawl_jobs" ADD COLUMN "background" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "app_private"."website_crawl_jobs" ADD COLUMN "leaseUntil" bigint;--> statement-breakpoint
ALTER TABLE "app_private"."website_crawl_jobs" ADD COLUMN "discovery" json;--> statement-breakpoint
ALTER TABLE "app_private"."catalog_sources" ADD CONSTRAINT "catalog_sources_organizationId_organizations_id_fk" FOREIGN KEY ("organizationId") REFERENCES "app_private"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_private"."catalog_sources" ADD CONSTRAINT "catalog_sources_createdByUserId_users_id_fk" FOREIGN KEY ("createdByUserId") REFERENCES "app_private"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "catalog_source_unique" ON "app_private"."catalog_sources" USING btree ("organizationId","provider","storeUrl");