import { useMemo, useState } from "react";
import { useLocation } from "wouter";
import { Check, Edit3, ExternalLink, PackageSearch, ScanSearch, ShieldX, Trash2, X } from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/components/PageHeader";
import { StatusPill } from "@/components/StatusPill";
import { WorkspaceGate } from "@/components/WorkspaceGate";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { useWorkspace } from "@/hooks/useWorkspace";
import { trpc } from "@/lib/trpc";

type Editable = { id: number; name: string; sku: string; category: string; description: string; productUrl: string; price: string; currency: string; specifications: string };

function CatalogContent() {
  const { organizationId } = useWorkspace();
  const [, setLocation] = useLocation();
  const utils = trpc.useUtils();
  const query = trpc.catalog.overview.useQuery({ organizationId: organizationId! }, { enabled: !!organizationId });
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("all");
  const [category, setCategory] = useState("all");
  const [selected, setSelected] = useState<number[]>([]);
  const [editing, setEditing] = useState<Editable | null>(null);
  const refresh = async () => Promise.all([utils.catalog.overview.invalidate(), utils.activity.list.invalidate()]);
  const review = trpc.catalog.reviewProduct.useMutation({ onSuccess: refresh, onError: error => toast.error(error.message) });
  const bulk = trpc.catalog.bulkReview.useMutation({ onSuccess: async result => { setSelected([]); await refresh(); toast.success(`${result.updated} products updated`); }, onError: error => toast.error(error.message) });
  const update = trpc.catalog.updateProduct.useMutation({ onSuccess: async () => { setEditing(null); await refresh(); toast.success("Product updated and returned to pending review"); }, onError: error => toast.error(error.message) });
  const cleanup = trpc.catalog.cleanupNonProducts.useMutation({ onSuccess: async result => { await refresh(); toast.success(result.removed ? `${result.removed} non-product records removed` : "No unapproved non-product records found"); }, onError: error => toast.error(error.message) });
  const remove = trpc.catalog.deleteProduct.useMutation({ onSuccess: async () => { await refresh(); toast.success("Catalog record removed"); }, onError: error => toast.error(error.message) });
  const categories = useMemo(() => Array.from(new Set((query.data?.products ?? []).map(product => product.category).filter((value): value is string => !!value))).sort(), [query.data?.products]);
  const products = useMemo(() => (query.data?.products ?? []).filter(product => (status === "all" || product.status === status) && (category === "all" || product.category === category) && `${product.name} ${product.sku ?? ""} ${product.category ?? ""}`.toLowerCase().includes(search.toLowerCase())), [query.data?.products, search, status, category]);
  const beginEdit = (product: (typeof products)[number]) => setEditing({ id: product.id, name: product.name, sku: product.sku ?? "", category: product.category ?? "", description: product.description ?? "", productUrl: product.productUrl, price: product.price ?? "", currency: product.currency ?? "", specifications: Object.entries(product.specifications).map(([name, value]) => `${name}: ${value}`).join("\n") });
  const save = () => {
    if (!editing) return;
    const specifications = Object.fromEntries(editing.specifications.split("\n").map(line => line.split(":" )).filter(parts => parts[0]?.trim() && parts.slice(1).join(":").trim()).map(parts => [parts[0]!.trim(), parts.slice(1).join(":").trim()]));
    update.mutate({ organizationId: organizationId!, productId: editing.id, product: { name: editing.name, sku: editing.sku || null, category: editing.category || null, description: editing.description || null, productUrl: editing.productUrl, price: editing.price || null, currency: editing.currency || null, specifications } });
  };

  return <><PageHeader eyebrow="Approved product truth" title="Product catalog" description="Review every discovered product, correct specifications, and approve only what campaign briefs may use." action={<div className="flex flex-wrap gap-2"><Button variant="outline" className="rounded-full" disabled={cleanup.isPending} onClick={() => { if (window.confirm("Remove all unapproved records that do not have verified product-page evidence? Approved products will be preserved.")) cleanup.mutate({ organizationId: organizationId! }); }}><ShieldX className="mr-2 h-4 w-4"/>Clean non-products</Button><Button className="rounded-full" onClick={() => setLocation("/app/import")}><ScanSearch className="mr-2 h-4 w-4"/>Import website</Button></div>}/><div className="mb-5 flex flex-col gap-3 xl:flex-row xl:items-center"><Input className="h-11 max-w-md" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search products, SKUs, or categories…"/><Select value={status} onValueChange={setStatus}><SelectTrigger className="h-11 w-full xl:w-44"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem><SelectItem value="pending">Pending</SelectItem><SelectItem value="approved">Approved</SelectItem><SelectItem value="rejected">Rejected</SelectItem></SelectContent></Select><Select value={category} onValueChange={setCategory}><SelectTrigger className="h-11 w-full xl:w-52"><SelectValue placeholder="All categories"/></SelectTrigger><SelectContent><SelectItem value="all">All categories</SelectItem>{categories.map(item => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select><div className="flex-1"/>{selected.length > 0 && <div className="flex gap-2"><Button variant="outline" onClick={() => bulk.mutate({ organizationId: organizationId!, productIds: selected, decision: "rejected" })}><X className="mr-2 h-4 w-4"/>Reject {selected.length}</Button><Button onClick={() => bulk.mutate({ organizationId: organizationId!, productIds: selected, decision: "approved" })}><Check className="mr-2 h-4 w-4"/>Approve {selected.length}</Button></div>}</div>
    {products.length === 0 ? <div className="surface grid min-h-[420px] place-items-center border-l-4 border-l-violet-400 text-center"><div><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-primary/10 text-primary"><PackageSearch className="h-6 w-6"/></div><h2 className="mt-5 text-xl font-semibold">No products in this view</h2><p className="mt-2 text-sm text-muted-foreground">Import a public company website or adjust the catalog filters.</p></div></div> : <div className="grid gap-4 md:grid-cols-2 2xl:grid-cols-3">{products.map(product => <article key={product.id} className={`surface overflow-hidden border-l-4 ${product.status === "approved" ? "border-l-emerald-500" : product.status === "rejected" ? "border-l-rose-400" : "border-l-amber-400"}`}><div className="flex gap-4 p-5"><Checkbox checked={selected.includes(product.id)} onCheckedChange={() => setSelected(selected.includes(product.id) ? selected.filter(id => id !== product.id) : [...selected, product.id])}/><div className="grid h-20 w-20 shrink-0 place-items-center overflow-hidden rounded-2xl bg-muted">{product.images[0] ? <img src={product.images[0].url} alt={product.name} className="h-full w-full object-contain"/> : <PackageSearch className="h-6 w-6 text-muted-foreground"/>}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><h2 className="line-clamp-2 font-semibold leading-tight">{product.name}</h2><p className="mt-1 text-xs text-muted-foreground">{product.category || "Uncategorized"}{product.sku ? ` · ${product.sku}` : ""}</p></div><StatusPill status={product.status}/></div><p className="mt-3 line-clamp-2 text-xs leading-5 text-muted-foreground">{product.description || "No product description was found."}</p></div></div><div className="border-t hairline px-5 py-4"><div className="mb-4 flex items-center justify-between text-xs"><span className="text-muted-foreground">{Object.keys(product.specifications).length} specifications</span><a href={product.productUrl} target="_blank" rel="noreferrer" className="flex items-center gap-1 text-primary">Source<ExternalLink className="h-3 w-3"/></a></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => beginEdit(product)}><Edit3 className="mr-1.5 h-3.5 w-3.5"/>Edit</Button><Button size="sm" variant="outline" onClick={() => { if (window.confirm(`Remove ${product.name} from the catalog?`)) remove.mutate({ organizationId: organizationId!, productId: product.id }); }}><Trash2 className="h-3.5 w-3.5"/></Button><Button size="sm" variant="outline" onClick={() => review.mutate({ organizationId: organizationId!, productId: product.id, decision: "rejected" })}><X className="h-3.5 w-3.5"/></Button><Button size="sm" className="flex-1" onClick={() => review.mutate({ organizationId: organizationId!, productId: product.id, decision: "approved" })}><Check className="mr-1.5 h-3.5 w-3.5"/>Approve</Button></div></div></article>)}</div>}
    <Dialog open={!!editing} onOpenChange={open => !open && setEditing(null)}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle className="font-editorial text-4xl font-normal">Edit product truth</DialogTitle></DialogHeader>{editing && <div className="grid gap-4 py-3 sm:grid-cols-2"><div className="sm:col-span-2"><Label>Name</Label><Input className="mt-2" value={editing.name} onChange={event => setEditing({ ...editing, name: event.target.value })}/></div><div><Label>SKU</Label><Input className="mt-2" value={editing.sku} onChange={event => setEditing({ ...editing, sku: event.target.value })}/></div><div><Label>Category</Label><Input className="mt-2" value={editing.category} onChange={event => setEditing({ ...editing, category: event.target.value })}/></div><div className="sm:col-span-2"><Label>Description</Label><Textarea className="mt-2 min-h-28" value={editing.description} onChange={event => setEditing({ ...editing, description: event.target.value })}/></div><div><Label>Price</Label><Input className="mt-2" value={editing.price} onChange={event => setEditing({ ...editing, price: event.target.value })}/></div><div><Label>Currency</Label><Input className="mt-2" value={editing.currency} onChange={event => setEditing({ ...editing, currency: event.target.value })}/></div><div className="sm:col-span-2"><Label>Source URL</Label><Input className="mt-2" value={editing.productUrl} onChange={event => setEditing({ ...editing, productUrl: event.target.value })}/></div><div className="sm:col-span-2"><Label>Specifications <span className="text-muted-foreground">(Name: value, one per line)</span></Label><Textarea className="mt-2 min-h-48 font-mono text-xs" value={editing.specifications} onChange={event => setEditing({ ...editing, specifications: event.target.value })}/></div><Button className="sm:col-span-2" onClick={save} disabled={!editing.name || !editing.productUrl || update.isPending}>Save changes for review</Button></div>}</DialogContent></Dialog></>;
}

export default function CatalogPage(){ return <WorkspaceGate><CatalogContent/></WorkspaceGate>; }
