import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { ArrowRight, Check, ShieldCheck, Sparkles } from "lucide-react";
import { useLocation } from "wouter";

const cards = [
  ["Concept 01", "from-violet-700 via-fuchsia-500 to-orange-200", "Built for the pace you set."],
  ["Concept 02", "from-slate-950 via-indigo-800 to-cyan-300", "Precision, without compromise."],
  ["Concept 03", "from-amber-100 via-rose-300 to-violet-700", "Make the next move unmistakable."],
];

export default function Home() {
  const { user } = useAuth(); const [, setLocation] = useLocation();
  const enter = () => user ? setLocation("/app") : startLogin();
  return <div className="min-h-screen overflow-hidden bg-[#f6f2eb] text-[#1b1820]">
    <nav className="mx-auto flex max-w-[1440px] items-center justify-between px-5 py-5 md:px-10"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#6c3cff] font-editorial text-xl text-white">F</div><span className="font-semibold tracking-tight">Frame</span></div><div className="hidden items-center gap-8 text-sm text-[#68616f] md:flex"><a href="#workflow">Workflow</a><a href="#control">Control</a><a href="#teams">Teams</a></div><Button onClick={enter} className="rounded-full px-5">{user ? "Open workspace" : "Start creating"}<ArrowRight className="ml-2 h-4 w-4" /></Button></nav>
    <main><section className="mx-auto grid max-w-[1440px] gap-14 px-5 pb-20 pt-12 md:px-10 lg:grid-cols-[.82fr_1.18fr] lg:items-center lg:pb-28 lg:pt-24"><div className="relative z-10"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-[#d9d0df] bg-white/60 px-3 py-1.5 text-xs font-semibold text-[#675e6e]"><Sparkles className="h-3.5 w-3.5 text-[#6c3cff]" /> AI creative, governed by people</div><h1 className="max-w-3xl font-editorial text-[clamp(4.4rem,8vw,8.6rem)] leading-[.78] tracking-[-.055em]">Create boldly.<br/><span className="italic text-[#6c3cff]">Publish safely.</span></h1><p className="mt-8 max-w-xl text-lg leading-8 text-[#625a68]">Turn approved briefs and brand assets into Meta-ready creative variants. Compare, comment, approve, and publish through one controlled team workflow.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button onClick={enter} size="lg" className="h-13 rounded-full px-7 text-base">Create your workspace<ArrowRight className="ml-2 h-4 w-4" /></Button><div className="flex items-center gap-2 px-3 text-sm text-[#6d6571]"><ShieldCheck className="h-4 w-4 text-emerald-700" /> No autonomous publishing</div></div></div><div className="relative min-h-[520px] lg:min-h-[660px]"><div className="absolute inset-0 rotate-[-3deg] rounded-[3rem] bg-[#e9e0ff]" /><div className="absolute inset-4 overflow-hidden rounded-[2.6rem] border border-white/70 bg-[#211d28] p-4 shadow-2xl lg:inset-8"><div className="mb-4 flex items-center justify-between px-3 py-2 text-white"><div><p className="text-xs uppercase tracking-[.18em] text-white/50">Spring launch</p><p className="mt-1 font-semibold">3 variants ready for review</p></div><span className="rounded-full bg-amber-300/15 px-3 py-1 text-xs text-amber-200">Awaiting approval</span></div><div className="grid h-[calc(100%-76px)] grid-cols-3 gap-3">{cards.map(([label,color,headline], index) => <div key={label} className={`relative overflow-hidden rounded-[1.8rem] bg-gradient-to-br ${color} ${index === 1 ? "translate-y-8" : index === 2 ? "translate-y-16" : ""}`}><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_28%,rgba(255,255,255,.65),transparent_18%)]"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/80 to-transparent p-4 pt-20 text-white"><p className="text-[10px] uppercase tracking-[.18em] text-white/60">{label}</p><p className="mt-2 font-editorial text-2xl leading-[.95]">{headline}</p><div className="mt-4 h-7 w-20 rounded-full bg-white/90" /></div></div>)}</div></div></div></section>
      <section id="workflow" className="bg-[#1c1921] px-5 py-24 text-white md:px-10 lg:py-32"><div className="mx-auto max-w-[1360px]"><p className="text-xs font-semibold uppercase tracking-[.2em] text-violet-300">One governed flow</p><div className="mt-5 grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><h2 className="font-editorial text-6xl leading-[.9] tracking-tight md:text-8xl">From brand truth<br/>to live ad.</h2><div className="grid gap-px overflow-hidden rounded-3xl bg-white/10 sm:grid-cols-2">{["Set your brand rules", "Approve the campaign brief", "Generate and compare", "Approve before publishing"].map((item, i) => <div key={item} className="bg-[#25212a] p-7"><span className="text-xs text-violet-300">0{i + 1}</span><h3 className="mt-10 text-xl font-semibold">{item}</h3><p className="mt-3 text-sm leading-6 text-white/55">Every transition is visible, permissioned, and recorded for the team.</p></div>)}</div></div></div></section>
      <section id="control" className="mx-auto max-w-[1360px] px-5 py-24 md:px-10 lg:py-32"><div className="surface grid overflow-hidden lg:grid-cols-2"><div className="p-8 md:p-14"><p className="eyebrow">Human control, designed in</p><h2 className="mt-5 font-editorial text-5xl leading-none md:text-7xl">The approval is not a checkbox. It is the system.</h2><p className="mt-6 max-w-xl text-base leading-7 text-muted-foreground">Generation accepts only approved inputs. Publishing revalidates the approved creative and exact frozen payload before it can touch Meta.</p><div className="mt-8 space-y-3">{["Role-based review decisions", "Approval invalidation after edits", "Tamper-evident activity chain"].map(item => <div key={item} className="flex items-center gap-3 text-sm font-medium"><span className="grid h-6 w-6 place-items-center rounded-full bg-emerald-100"><Check className="h-3.5 w-3.5 text-emerald-700" /></span>{item}</div>)}</div></div><div className="min-h-[460px] bg-[radial-gradient(circle_at_35%_30%,#a68cff,transparent_24%),radial-gradient(circle_at_75%_68%,#ffb88a,transparent_28%),#211d28] p-8"><div className="ml-auto mt-20 max-w-sm rounded-3xl border border-white/15 bg-black/35 p-5 text-white backdrop-blur-xl"><div className="flex items-center justify-between"><p className="font-semibold">Publish request</p><span className="rounded-full bg-amber-300/15 px-2.5 py-1 text-[10px] uppercase tracking-wider text-amber-200">Awaiting approval</span></div><div className="my-5 space-y-3 text-sm text-white/60"><p>Creative <span className="float-right text-white">Concept 02</span></p><p>Destination <span className="float-right text-white">Meta / Prospecting</span></p><p>Action <span className="float-right text-white">Create ad</span></p></div><div className="rounded-2xl bg-white/10 p-4 text-xs leading-5 text-white/70">The approved payload is frozen. Any change invalidates the approval.</div><div className="mt-4 h-10 rounded-xl bg-emerald-400" /></div></div></div></section>
    </main></div>;
}
