import { randomUUID } from "node:crypto";
import sharp from "sharp";
import { and, eq, inArray } from "drizzle-orm";
import { afterAll, beforeAll, describe, expect, it, vi } from "vitest";
const storage = vi.hoisted(() => ({ count: 0 }));
vi.mock("./storage", async original => ({ ...(await original<typeof import("./storage")>()), storagePut: async (key: string) => { storage.count++; return { key, url: "/media/" + key }; } }));
import { activityEvents, brandAssets, brandKits, organizationMemberships, organizations, users } from "../drizzle/schema";
import { getDb } from "./db";
import { appRouter } from "./routers";
import type { TrpcContext } from "./_core/context";
import { verifyActivityChain } from "./lib/activity";
let organizationId = 0;
let otherOrganizationId = 0;
let image = "";
const userIds: number[] = [];
let owner: ReturnType<typeof appRouter.createCaller>;
let creator: ReturnType<typeof appRouter.createCaller>;
let outsider: ReturnType<typeof appRouter.createCaller>;
let key = "";
const database = async () => { const db = await getDb(); if (!db) throw new Error("Isolated integration database required"); return db; };
beforeAll(async () => {
  const db = await database(); const suffix = randomUUID(); const now = Date.now();
  const people = await db.insert(users).values(["owner", "creator", "outsider"].map(name => ({ openId: `library-${name}-${suffix}`, name, email: `${name}@example.test`, loginMethod: "test" }))).returning();
  userIds.push(...people.map(person => person.id));
  const orgs = await db.insert(organizations).values(["main", "other"].map(name => ({ name: `Library ${name}`, slug: `library-${name}-${suffix}`, createdByUserId: people[0].id, createdAtMs: now }))).returning();
  organizationId = orgs[0].id; otherOrganizationId = orgs[1].id;
  await db.insert(organizationMemberships).values([{ userId: people[0].id, organizationId, role: "owner", status: "active", createdAtMs: now }, { userId: people[1].id, organizationId, role: "creator", status: "active", createdAtMs: now }, { userId: people[2].id, organizationId: otherOrganizationId, role: "owner", status: "active", createdAtMs: now }]);
  await db.insert(brandKits).values(orgs.map(org => ({ organizationId: org.id, name: "Library test", colors: ["#ffffff"], fonts: ["Inter"], voice: "Clear", requiredClaims: "", prohibitedContent: "", status: "active" as const, updatedByUserId: people[0].id, updatedAtMs: now })));
  [owner, creator, outsider] = people.map(user => appRouter.createCaller({ user, req: {}, res: {} } as TrpcContext));
  image = (await sharp({ create: { width: 8, height: 8, channels: 4, background: "white" } }).png().toBuffer()).toString("base64");
});
afterAll(async () => {
  if (!organizationId) return;
  const db = await database();
  for (const table of [activityEvents, brandAssets, brandKits, organizationMemberships]) await db.delete(table).where(inArray(table.organizationId, [organizationId, otherOrganizationId]));
  await db.delete(organizations).where(inArray(organizations.id, [organizationId, otherOrganizationId]));
  await db.delete(users).where(inArray(users.id, userIds));
});
const uploadInput = () => ({ organizationId, name: "Launch image.png", mimeType: "image/png" as const, base64: image, purpose: "finished" as const });
const current = async () => { const asset = (await owner.assetLibrary.list({ organizationId })).find(asset => asset.key === key); if (!asset) throw new Error("Missing test asset"); return asset; };
describe.sequential("shared asset library workflow", () => {
  it("uploads into the shared library as a draft", async () => { const result = await creator.assetLibrary.upload(uploadInput()); key = result.key; const asset = await current(); expect(asset.state).toBe("draft"); expect(asset.purpose).toBe("finished"); expect(asset.mediaType).toBe("image"); });
  it("does not approve a draft before submission", async () => { const asset = await current(); await expect(owner.assetLibrary.review({ organizationId, key, revision: asset.revision, decision: "approved" })).rejects.toMatchObject({ code: "PRECONDITION_FAILED" }); });
  it("queues an explicit submission", async () => { const asset = await current(); await creator.assetLibrary.submit({ organizationId, key, revision: asset.revision }); expect((await current()).state).toBe("needs_review"); });
  it("denies creator self-approval", async () => { const asset = await current(); await expect(creator.assetLibrary.review({ organizationId, key, revision: asset.revision, decision: "approved" })).rejects.toMatchObject({ code: "FORBIDDEN" }); });
  it("requires a note for changes requested", async () => { const asset = await current(); await expect(owner.assetLibrary.review({ organizationId, key, revision: asset.revision, decision: "changes_requested" })).rejects.toMatchObject({ code: "BAD_REQUEST" }); });
  it("records a change request with feedback", async () => { const asset = await current(); await owner.assetLibrary.review({ organizationId, key, revision: asset.revision, decision: "changes_requested", note: "Use the new headline" }); expect((await current()).state).toBe("changes_requested"); expect((await owner.assetLibrary.history({ organizationId, key }))[0].body).toBe("Use the new headline"); });
  it("rejects stale review decisions", async () => { const asset = await current(); await creator.assetLibrary.submit({ organizationId, key, revision: asset.revision }); await expect(owner.assetLibrary.review({ organizationId, key, revision: asset.revision, decision: "approved" })).rejects.toMatchObject({ code: "CONFLICT" }); });
  it("approves the current submitted version", async () => { const asset = await current(); await owner.assetLibrary.review({ organizationId, key, revision: asset.revision, decision: "approved", note: "Ready for use" }); expect((await current()).state).toBe("approved"); });
  it("keeps the original approved when uploading a new version", async () => { const result = await creator.assetLibrary.upload({ ...uploadInput(), parentKey: key, name: "New version.png" }); const assets = await owner.assetLibrary.list({ organizationId }); const child = assets.find(asset => asset.key === result.key); expect(child?.state).toBe("draft"); expect(child?.parentKey).toBe(key); expect((await current()).state).toBe("approved"); });
  it("requires permission confirmation for UGC", async () => { const before = storage.count; await expect(creator.assetLibrary.upload({ ...uploadInput(), isUgc: true })).rejects.toMatchObject({ code: "BAD_REQUEST" }); expect(storage.count).toBe(before); });
  it("saves UGC as a classification rather than a second copy", async () => { const result = await creator.assetLibrary.upload({ ...uploadInput(), isUgc: true, usagePermissionConfirmed: true }); const assets = await owner.assetLibrary.list({ organizationId }); expect(assets.filter(asset => asset.key === result.key)).toHaveLength(1); expect(assets.find(asset => asset.key === result.key)?.isUgc).toBe(true); });
  it("rejects MIME mismatch before storing bytes", async () => { const before = storage.count; await expect(creator.assetLibrary.upload({ ...uploadInput(), mimeType: "video/mp4" })).rejects.toMatchObject({ code: "BAD_REQUEST" }); expect(storage.count).toBe(before); });
  it("denies cross-workspace reads and history", async () => { await expect(outsider.assetLibrary.list({ organizationId })).rejects.toMatchObject({ code: "FORBIDDEN" }); await expect(outsider.assetLibrary.history({ organizationId: otherOrganizationId, key })).rejects.toMatchObject({ code: "NOT_FOUND" }); });
  it("denies using a foreign asset as a parent version", async () => { await expect(outsider.assetLibrary.upload({ ...uploadInput(), organizationId: otherOrganizationId, parentKey: key })).rejects.toMatchObject({ code: "NOT_FOUND" }); });
  it("records comments without changing approval", async () => { const asset = await current(); await creator.assetLibrary.comment({ organizationId, key, revision: asset.revision, body: "Use this for next week's plan" }); expect((await current()).state).toBe("approved"); expect((await owner.assetLibrary.history({ organizationId, key }))[0].body).toContain("next week"); });
  it("keeps the audit chain valid", async () => { const db = await database(); const events = await db.select().from(activityEvents).where(eq(activityEvents.organizationId, organizationId)); expect(verifyActivityChain(events)).toBe(true); });
  it("invalidates a stored library approval after changed content", async () => { const db = await database(); await db.update(brandAssets).set({ name: "Content changed externally" }).where(and(eq(brandAssets.organizationId, organizationId), eq(brandAssets.id, Number(key.split(":")[1])))); expect((await current()).state).toBe("draft"); });
});
