import { randomUUID } from "node:crypto";
import sharp from "sharp";
import { and, eq, inArray } from "drizzle-orm";
import { afterAll, beforeAll, describe, expect, it, vi } from "vitest";
const storage = vi.hoisted(() => ({ count: 0 }));
vi.mock("./storage", async original => ({ ...(await original<typeof import("./storage")>()), storagePut: async (key: string) => { storage.count++; return { key, url: "/media/" + key }; } }));
import { activityEvents, brandAssets, brandKits, campaignBriefs, creativeJobs, creativeVariants, organizationMemberships, organizations, users } from "../drizzle/schema";
import { getDb } from "./db";
import { appRouter } from "./routers";
import type { TrpcContext } from "./_core/context";
import { verifyActivityChain } from "./lib/activity";
let organizationId = 0, otherOrganizationId = 0, image = "", key = "", generatedKey = "";
const userIds: number[] = [];
let owner: ReturnType<typeof appRouter.createCaller>, creator: typeof owner, outsider: typeof owner, reviewer: typeof owner, publisher: typeof owner, admin: typeof owner;
const database = async () => { const db = await getDb(); if (!db) throw new Error("Isolated integration database required"); return db; };
beforeAll(async () => {
  const db = await database(), suffix = randomUUID(), now = Date.now();
  const names = ["owner", "creator", "outsider", "reviewer", "publisher", "admin"];
  const people = await db.insert(users).values(names.map(name => ({ openId: `library-${name}-${suffix}`, name, email: `${name}@example.test`, loginMethod: "test" }))).returning();
  userIds.push(...people.map(person => person.id));
  const orgs = await db.insert(organizations).values(["main", "other"].map(name => ({ name: `Library ${name}`, slug: `library-${name}-${suffix}`, createdByUserId: people[0].id, createdAtMs: now }))).returning();
  organizationId = orgs[0].id; otherOrganizationId = orgs[1].id;
  const roles = ["owner", "creator", "owner", "reviewer", "publisher", "admin"] as const;
  await db.insert(organizationMemberships).values(people.map((person, i) => ({ userId: person.id, organizationId: i === 2 ? otherOrganizationId : organizationId, role: roles[i], status: "active" as const, createdAtMs: now })));
  await db.insert(brandKits).values(orgs.map(org => ({ organizationId: org.id, name: "Library test", colors: ["#ffffff"], fonts: ["Inter"], voice: "Clear", requiredClaims: "", prohibitedContent: "", status: "active" as const, updatedByUserId: people[0].id, updatedAtMs: now })));
  [owner, creator, outsider, reviewer, publisher, admin] = people.map(user => appRouter.createCaller({ user, req: {}, res: {} } as TrpcContext));
  image = (await sharp({ create: { width: 8, height: 8, channels: 4, background: "white" } }).png().toBuffer()).toString("base64");
  const [brief] = await db.insert(campaignBriefs).values({ organizationId, name: "Generated work", audience: "Test", offer: "Test", placements: [], formats: [], creativeDirection: "Test", assetIds: [], createdByUserId: people[1].id, createdAtMs: now, updatedAtMs: now }).returning();
  const [job] = await db.insert(creativeJobs).values({ organizationId, briefId: brief.id, status: "completed", inputHash: "a".repeat(64), briefSnapshot: {}, assetSnapshot: [], requestedByUserId: people[1].id, createdAtMs: now }).returning();
  const [variant] = await db.insert(creativeVariants).values({ organizationId, briefId: brief.id, jobId: job.id, name: "Unsubmitted generated image", concept: "Test", primaryText: "Verified text", headline: "Test", callToAction: "LEARN_MORE", format: "square_1_1", imageUrl: "/media/test/generated.png", imageStorageKey: "test/generated.png", status: "pending", createdAtMs: now }).returning();
  generatedKey = `creative:${variant.id}`;
});
afterAll(async () => {
  if (!organizationId) return;
  const db = await database();
  for (const table of [activityEvents, creativeVariants, creativeJobs, campaignBriefs, brandAssets, brandKits, organizationMemberships]) await db.delete(table).where(inArray(table.organizationId, [organizationId, otherOrganizationId]));
  await db.delete(organizations).where(inArray(organizations.id, [organizationId, otherOrganizationId]));
  await db.delete(users).where(inArray(users.id, userIds));
});
const uploadInput = () => ({ organizationId, name: "Launch image.png", mimeType: "image/png" as const, base64: image, purpose: "finished" as const });
const current = async (reference = key) => { const asset = (await owner.assetLibrary.studioList({ organizationId })).find(asset => asset.key === reference); if (!asset) throw new Error("Missing test asset"); return asset; };
describe.sequential("Studio to Asset Library handoff", () => {
  it("keeps generated experiments in Studio and out of the library", async () => { expect((await current(generatedKey)).state).toBe("draft"); expect(await owner.assetLibrary.list({ organizationId })).toEqual([]); });
  it("uploads as a durable Studio draft, without adding it to the library", async () => { key = (await creator.assetLibrary.upload(uploadInput())).key; const asset = await current(); expect(asset.state).toBe("draft"); expect(asset.purpose).toBe("finished"); expect(asset.mediaType).toBe("image"); expect((await owner.assetLibrary.list({ organizationId })).some(a => a.key === key)).toBe(false); });
  it("denies non-creators access to the working-draft collection", async () => { await expect(reviewer.assetLibrary.studioList({ organizationId })).rejects.toMatchObject({ code: "FORBIDDEN" }); await expect(publisher.assetLibrary.studioList({ organizationId })).rejects.toMatchObject({ code: "FORBIDDEN" }); });
  it("does not expose draft history to non-creating roles", async () => { await expect(reviewer.assetLibrary.history({ organizationId, key })).rejects.toMatchObject({ code: "NOT_FOUND" }); });
  it("requires explicit submission before ordinary library approval", async () => { const asset = await current(); await expect(owner.assetLibrary.review({ organizationId, key, revision: asset.revision, decision: "approved" })).rejects.toMatchObject({ code: "PRECONDITION_FAILED" }); });
  it("blocks forged direct-approval requests by a creator", async () => { const asset = await current(); await expect(creator.assetLibrary.approveAndAdd({ organizationId, key, revision: asset.revision })).rejects.toMatchObject({ code: "FORBIDDEN" }); expect((await current()).state).toBe("draft"); });
  it("adds the same record to Needs Review after submission", async () => { const before = storage.count, asset = await current(); await creator.assetLibrary.submit({ organizationId, key, revision: asset.revision }); const inLibrary = (await owner.assetLibrary.list({ organizationId })).find(a => a.key === key); expect(inLibrary?.state).toBe("needs_review"); expect(inLibrary?.url).toBe(asset.url); expect(storage.count).toBe(before); });
  it("denies creator self-approval and publisher approval", async () => { const asset = await current(); for (const caller of [creator, publisher]) await expect(caller.assetLibrary.review({ organizationId, key, revision: asset.revision, decision: "approved" })).rejects.toMatchObject({ code: "FORBIDDEN" }); });
  it("requires feedback when requesting changes", async () => { const asset = await current(); await expect(reviewer.assetLibrary.review({ organizationId, key, revision: asset.revision, decision: "changes_requested" })).rejects.toMatchObject({ code: "BAD_REQUEST" }); });
  it("returns changes to Studio and retains review history", async () => { const asset = await current(); await reviewer.assetLibrary.review({ organizationId, key, revision: asset.revision, decision: "changes_requested", note: "Use the new headline" }); expect((await current()).state).toBe("changes_requested"); expect((await owner.assetLibrary.history({ organizationId, key }))[0].body).toBe("Use the new headline"); expect((await owner.assetLibrary.list({ organizationId })).find(a => a.key === key)?.state).toBe("changes_requested"); });
  it("rejects stale decisions after resubmission", async () => { const asset = await current(); await creator.assetLibrary.submit({ organizationId, key, revision: asset.revision }); await expect(reviewer.assetLibrary.review({ organizationId, key, revision: asset.revision, decision: "approved" })).rejects.toMatchObject({ code: "CONFLICT" }); });
  it("lets an authorized reviewer approve the submitted version", async () => { const asset = await current(); await reviewer.assetLibrary.review({ organizationId, key, revision: asset.revision, decision: "approved", note: "Ready for use" }); expect((await current()).state).toBe("approved"); });
  it("preserves the approved original when uploading a new draft version", async () => { const result = await creator.assetLibrary.upload({ ...uploadInput(), parentKey: key, name: "New version.png" }); const child = await current(result.key); expect(child.state).toBe("draft"); expect(child.parentKey).toBe(key); expect((await current()).state).toBe("approved"); expect((await owner.assetLibrary.list({ organizationId })).some(a => a.key === child.key)).toBe(false); });
  it("requires UGC usage permission before storing files", async () => { const before = storage.count; await expect(creator.assetLibrary.upload({ ...uploadInput(), isUgc: true })).rejects.toMatchObject({ code: "BAD_REQUEST" }); expect(storage.count).toBe(before); });
  it("stores UGC once as a classification", async () => { const result = await creator.assetLibrary.upload({ ...uploadInput(), isUgc: true, usagePermissionConfirmed: true }); const assets = await owner.assetLibrary.studioList({ organizationId }); expect(assets.filter(a => a.key === result.key)).toHaveLength(1); expect(assets.find(a => a.key === result.key)?.isUgc).toBe(true); });
  it("rejects MIME mismatch before storing files", async () => { const before = storage.count; await expect(creator.assetLibrary.upload({ ...uploadInput(), mimeType: "video/mp4" })).rejects.toMatchObject({ code: "BAD_REQUEST" }); expect(storage.count).toBe(before); });
  it("denies cross-workspace lists and history", async () => { await expect(outsider.assetLibrary.list({ organizationId })).rejects.toMatchObject({ code: "FORBIDDEN" }); await expect(outsider.assetLibrary.history({ organizationId: otherOrganizationId, key })).rejects.toMatchObject({ code: "NOT_FOUND" }); });
  it("denies a foreign parent version", async () => { await expect(outsider.assetLibrary.upload({ ...uploadInput(), organizationId: otherOrganizationId, parentKey: key })).rejects.toMatchObject({ code: "NOT_FOUND" }); });
  it("records comments without changing approval", async () => { const asset = await current(); await creator.assetLibrary.comment({ organizationId, key, revision: asset.revision, body: "Use for next week's plan" }); expect((await current()).state).toBe("approved"); expect((await owner.assetLibrary.history({ organizationId, key }))[0].body).toContain("next week"); });
  it("invalidates changed approved content and removes it from the library", async () => { const db = await database(); await db.update(brandAssets).set({ name: "Changed externally" }).where(and(eq(brandAssets.organizationId, organizationId), eq(brandAssets.id, Number(key.split(":")[1])))); expect((await current()).state).toBe("draft"); expect((await owner.assetLibrary.list({ organizationId })).some(a => a.key === key)).toBe(false); });
  it("supports owner direct approval with both audit events recorded", async () => { const asset = await current(); await owner.assetLibrary.approveAndAdd({ organizationId, key, revision: asset.revision }); expect((await current()).state).toBe("approved"); const history = await owner.assetLibrary.history({ organizationId, key }); expect(history.slice(0, 2).map(e => e.action).sort()).toEqual(["approved", "submitted"]); });
  it("checks approved-upload permission before any storage write", async () => { const before = storage.count; await expect(creator.assetLibrary.upload({ ...uploadInput(), disposition: "approve" })).rejects.toMatchObject({ code: "FORBIDDEN" }); expect(storage.count).toBe(before); });
  it("allows explicit admin upload-and-approve", async () => { const result = await admin.assetLibrary.upload({ ...uploadInput(), disposition: "approve" }); expect(result.state).toBe("approved"); expect((await owner.assetLibrary.list({ organizationId })).find(a => a.key === result.key)?.state).toBe("approved"); });
  it("lets a creator upload-and-submit, never automatically approve", async () => { const result = await creator.assetLibrary.upload({ ...uploadInput(), disposition: "submit" }); expect(result.state).toBe("needs_review"); expect((await current(result.key)).reviewedByUserId).toBe(null); });
  it("does not let a reviewer bypass Studio permissions with direct approval", async () => { const asset = await current(generatedKey); await expect(reviewer.assetLibrary.approveAndAdd({ organizationId, key: asset.key, revision: asset.revision })).rejects.toMatchObject({ code: "FORBIDDEN" }); });
  it("submits generated work without duplicating creative records or media", async () => { const db = await database(), before = await db.select().from(creativeVariants).where(eq(creativeVariants.organizationId, organizationId)), asset = await current(generatedKey); await creator.assetLibrary.submit({ organizationId, key: asset.key, revision: asset.revision }); expect((await owner.assetLibrary.list({ organizationId })).filter(a => a.key === asset.key)).toHaveLength(1); expect(await db.select().from(creativeVariants).where(eq(creativeVariants.organizationId, organizationId))).toHaveLength(before.length); });
  it("rejects replayed submission revisions", async () => { const asset = await current(generatedKey); await expect(creator.assetLibrary.submit({ organizationId, key: asset.key, revision: asset.revision })).rejects.toMatchObject({ code: "PRECONDITION_FAILED" }); });
  it("keeps the transactional audit chain valid", async () => { const db = await database(); const events = await db.select().from(activityEvents).where(eq(activityEvents.organizationId, organizationId)); expect(verifyActivityChain(events)).toBe(true); });
});
